/**
 * This script reads FOCAL hit information from a ROOT file generated by O2 simulation.
 * It accesses the "o2sim" TTree in "o2sim_HitsFOC.root", retrieves the position of
 * each FOCHit and plots:
 *   - Hits vs Z          (1D)
 *   - Hits vs X-Y        (2D)
 *   - Hits vs Y-Z        (2D)
 *   - Hits vs X-Y-Z      (3D)
 */

void focHits_pos() {
    // Open the ROOT file
    TFile* file = TFile::Open("../o2sim_HitsFOC.root");
    if (!file || file->IsZombie()) {
        std::cerr << "Error opening file 'o2sim_HitsFOC.root'." << std::endl;
        return;
    }
    std::cout << "File opened successfully." << std::endl;

    // Retrieve the TTree
    TTree* tree = (TTree*)file->Get("o2sim");
    if (!tree) {
        std::cerr << "Tree 'o2sim' not found." << std::endl;
        return;
    }
    std::cout << "Tree found." << std::endl;

    // Setup the reader and the relevant branches
    TTreeReader reader(tree);
    TTreeReaderArray<Float_t> x(reader, "FOCHit.mPos.fCoordinates.fX");
    TTreeReaderArray<Float_t> y(reader, "FOCHit.mPos.fCoordinates.fY");
    TTreeReaderArray<Float_t> z(reader, "FOCHit.mPos.fCoordinates.fZ");

    // Create histograms
    TH1F* hZ   = new TH1F("hZ",   "Hit count vs Z position;Z [cm];Number of Hits", 1000, 700, 820);
    TH2F* hXY  = new TH2F("hXY",  "Hit map in XY plane;X [cm];Y [cm]",             1000, -50, 50, 1000, -50, 50);
    TH2F* hYZ  = new TH2F("hYZ",  "Hit map in YZ plane;Z [cm];Y [cm]",             1000, 700, 820, 1000, -50, 50);
    TH3F* hXYZ = new TH3F("hXYZ", "3D hit distribution;X [cm];Y [cm];Z [cm]",      100, -50, 50, 100, -50, 50, 100, 700, 820);

    // Loop through events and fill histograms
    int i = 0;
    while (reader.Next()) {
        int nHits = x.GetSize();

        for (int j = 0; j < nHits; ++j) {
            hZ->Fill(z[j]);
            hXY->Fill(x[j], y[j]);
            hYZ->Fill(z[j], y[j]);    // note: z is x-axis, y is y-axis
            hXYZ->Fill(x[j], y[j], z[j]);
        }

        i++;
    }

    std::cout << "Processed " << i << " events." << std::endl;

    // Draw all histograms
    gStyle->SetOptStat(1110);

    // Canvas 1: Z histogram
    TCanvas* c1 = new TCanvas("c1", "Hits vs Z", 800, 600);
    hZ->Draw();

    // Canvas 2: XY
    TCanvas* c2 = new TCanvas("c2", "Hits in XY", 800, 600);
    hXY->SetStats(0);
    hXY->Draw("COLZ");

    // Canvas 3: YZ
    TCanvas* c3 = new TCanvas("c3", "Hits in YZ", 800, 600);
    hYZ->SetStats(0);
    hYZ->Draw("COLZ");

    // Canvas 4: 3D XYZ
    TCanvas* c4 = new TCanvas("c4", "Hits in XYZ (3D)", 800, 600);
    gStyle->SetPalette(kRainBow); // Optional: colorful 3D
    hXYZ->Draw("BOX2Z");

    // Update canvases
    c1->Update();
    c2->Update();
    c3->Update();
    c4->Update();
}
