/**
 * This script reads FOCAL hit information from a ROOT file generated by O2 simulation.
 * Specifically, it accesses the "o2sim" TTree from the file "o2sim_HitsFOC.root",
 * retrieves the Track ID and the x-coordinate of each hit (FOCHit), and prints them
 * event by event. It also reports the total number of hits per event.
 * 
 * The script uses TTreeReader for safe and modern access to ROOT TTree branches.
 */

void focHits() {
    // Open the ROOT file containing FOCAL hit data
    TFile* file = TFile::Open("../o2sim_HitsFOC.root");
    
    // Check if the file was opened successfully
    if (!file || file->IsZombie()) {
        std::cerr << "Error opening file 'o2sim_HitsFOC.root'." << std::endl;
        return;
    } else {
        std::cout << "File 'o2sim_HitsFOC.root' opened successfully." << std::endl;
    }

    // Get the TTree named "o2sim" from the file
    TTree* tree = (TTree*)file->Get("o2sim");

    // Check if the tree was found
    if (!tree) {
        std::cerr << "Tree 'o2sim' not found in file." << std::endl;
        return;
    } else {
        std::cout << "Tree 'o2sim' found." << std::endl;
    }

    // Create a TTreeReader to iterate over the entries of the tree
    TTreeReader reader(tree);

    // Set up readers for the arrays of TrackID and x position from FOCHit
    TTreeReaderArray<Int_t> mTrackID(reader, "FOCHit.mTrackID");
    TTreeReaderArray<Float_t> x(reader, "FOCHit.mPos.fCoordinates.fX");

    int i = 0; // Event index counter

    // Loop over all events in the tree
    while (reader.Next()) {
        int nHits = mTrackID.GetSize(); // Number of hits in the current event
        std::cout << "🔹 Event " << i << " with " << nHits << " hits:" << std::endl;

        // Loop over each hit and print the Track ID and x-coordinate
        for (int j = 0; j < nHits; ++j) {
            std::cout << "    • Hit " << j << " - Track ID: " << mTrackID[j]
                      << " | x: " << x[j] << std::endl;
        }

        i++; // Go to next event
    }

    // Print total number of processed events
    std::cout << "Finished reading " << i << " events successfully." << std::endl;
}
