/**
 * This script reads FOCAL hit information from a ROOT file generated by O2 simulation.
 * It accesses the "o2sim" TTree in "o2sim_HitsFOC.root", retrieves the z-position of
 * each FOCHit and plots a histogram showing the number of hits as a function of z.
 */

void focHits_ZPlot() {
    // Open the ROOT file
    TFile* file = TFile::Open("../o2sim_HitsFOC.root");
    if (!file || file->IsZombie()) {
        std::cerr << "Error opening file 'o2sim_HitsFOC.root'." << std::endl;
        return;
    }
    std::cout << "File opened successfully." << std::endl;

    // Retrieve the TTree
    TTree* tree = (TTree*)file->Get("o2sim");
    if (!tree) {
        std::cerr << "Tree 'o2sim' not found." << std::endl;
        return;
    }
    std::cout << "Tree found." << std::endl;

    // Setup the reader and the relevant branches
    TTreeReader reader(tree);
    TTreeReaderArray<Float_t> z(reader, "FOCHit.mPos.fCoordinates.fZ");

    // Create a histogram for hit position along Z
    TH1F* hZ = new TH1F("hZ", "Hit count vs Z position;Z [cm];Number of Hits", 200, 700, 820);

    // Loop through events and fill histogram
    int i = 0;
    while (reader.Next()) {
        int nHits = z.GetSize();
        //std::cout << "Event " << i << " with " << nHits << " hits." << std::endl;

        for (int j = 0; j < nHits; ++j) {
            hZ->Fill(z[j]);
        }

        i++;
    }

    std::cout << "Processed " << i << " events." << std::endl;

    // Draw the histogram
    gStyle->SetOptStat(1110); // optional: show stats box
    hZ->Draw();
}
